# Generated by Django 4.0.6 on 2022-07-18 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money_data', '0002_moneylog_delete_moneyamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneylog',
            name='info',
        ),
    ]
