# Generated by Django 4.0.6 on 2022-07-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_data', '0004_moneylog_money_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneylog',
            name='anonymouse',
            field=models.BooleanField(default=True),
        ),
    ]
