# Generated by Django 4.0.6 on 2022-07-18 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money_data', '0005_moneylog_anonymouse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneylog',
            old_name='anonymouse',
            new_name='anonymous',
        ),
    ]
