# Generated by Django 4.0.6 on 2022-07-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_data', '0006_rename_anonymouse_moneylog_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneylog',
            name='money_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='moneylog',
            name='money_made',
            field=models.FloatField(),
        ),
    ]
